---
- hosts: all 
  gather_facts: no
  become: yes
  tasks: 
  - name: Wait for ssh
    wait_for_connection:
      timeout: 900
  - name: Setup dep key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
  - name: Setup K8s dep
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list
  - name: Update and upgrade apt
    apt:
      force_apt_get: 'yes'
      update_cache: 'yes'
      upgrade: 'yes'
  - name: Install dependencies
    apt:
      force_apt_get: yes
      pkg:
      - docker.io
      - kubelet
      - kubeadm
      - kubectl
  - name: Start docker service 
    systemd:
      name: docker
      state: started
      enabled: yes
  - name: Set sysctl
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: '1'
      state: present
      reload: yes
- hosts: k8s-master1
  gather_facts: no
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
  - name: copy kubeadm-config
    copy:
      src: kubeadm.config
      dest: /tmp/
  - name: Kubeadm init
    tags: "init"
    shell: kubeadm init --upload-certs --config /tmp/kubeadm.config
  - name: Install CNI
    tags: "init"
    shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  - name: Fetching admin.conf
    tags: kubeadm_init
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: ~/.kube/config
      flat: yes
- hosts: all
  gather_facts: no
  become: yes
  tags: "cloud-config"
  tasks:
  - name: Copy cloud-config
    copy:
      src: cloud-config
      dest: /etc/kubernetes/
  - name: copy kublet extra config
    copy:
      src: kubelet
      dest: /etc/default/   
- hosts: workers
  gather_facts: no
  become: yes
  tags: "join"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
  - name: Generate join token
    shell: kubeadm token create --print-join-command
    register: join_command
    delegate_to: "{{ groups['masters'][0] }}"
  - set_fact:
      kubeadm_join: "{{ join_command.stdout }}"
  - name: Run kubeadm join
    shell: "{{ kubeadm_join }}" 
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Ensure the fqdn name of api
    tags:
    - local_kube
    lineinfile:
      path: ~/.kube/config
      regexp: '\s\s\s\sserver: https:\/\/192\.168\.0\.11:6443'
      line: '    server: https://api.k8s.ysung.tips:6443'
  - name: create gce sc
    shell: kubectl apply -f ./gcp_pd_sc_fast.yaml
